// Code generated by "stringer -type=CurrencyCode -trimprefix=Currency"; DO NOT EDIT.

package model

import "strconv"

const _CurrencyCode_name = "USDEURRUB"

var _CurrencyCode_index = [...]uint8{0, 3, 6, 9}

func (i CurrencyCode) String() string {
	i -= 1
	if i < 0 || i >= CurrencyCode(len(_CurrencyCode_index)-1) {
		return "CurrencyCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CurrencyCode_name[_CurrencyCode_index[i]:_CurrencyCode_index[i+1]]
}
